version: '2.1'

services:

  metagenscope-db:
    container_name: metagenscope-db
    build: https://${GITHUB_TOKEN}@github.com/bchrobot/metagenscope-server.git#master:app/db
    ports:
      - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      # These are not used in production so it is fine to commit them
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  metagenscope-service:
    container_name: metagenscope-service
    build: https://${GITHUB_TOKEN}@github.com/bchrobot/metagenscope-server.git
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      # Environment: development | testing | staging | production
      - APP_SETTINGS=development
      - SECRET_KEY=my_precious
      - DATABASE_URL=postgres://postgres:postgres@metagenscope-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@metagenscope-db:5432/users_test
    depends_on:
      metagenscope-db:
        condition: service_healthy
    links:
      - metagenscope-db

  web-service:
    container_name: web-service
    build: https://${GITHUB_TOKEN}@github.com/bchrobot/metagenscope-client.git
    ports:
      - '3007:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      metagenscope-service:
        condition: service_started
    links:
      - metagenscope-service
