version: '2.1'

services:

  metagenscope-db:
    container_name: metagenscope-db
    image: metagenscope/metagenscope-db:emptyfish
    ports:
      - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      # Pull these from .env
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: exit 0

  metagenscope-service:
    container_name: metagenscope-service
    image: metagenscope/metagenscope-service:emptyfish
    command: gunicorn -b 0.0.0.0:5000 manage:app
    ports:
      - '5000'
    environment:
      # Environment: development | testing | staging | production
      - APP_SETTINGS=production
      - SECRET_KEY
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@metagenscope-db:5432/metagenscope_prod
      - DATABASE_TEST_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@metagenscope-db:5432/metagenscope_test
    depends_on:
      metagenscope-db:
        condition: service_healthy
    links:
      - metagenscope-db

  web-service:
    container_name: web-service
    image: metagenscope/metagenscope-client:emptyfish
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    depends_on:
      metagenscope-service:
        condition: service_started

  nginx:
    container_name: nginx
    image: metagenscope/metagenscope-nginx:emptyfish
    restart: always
    ports:
      - 80:80
    depends_on:
      metagenscope-service:
        condition: service_started
      web-service:
        condition: service_started
    links:
      - metagenscope-service
      - web-service
