version: '2.1'

services:

  metagenscope-db:
    build: https://${GITHUB_TOKEN}@github.com/bchrobot/metagenscope-server.git#master:app/db

  metagenscope-service:
    build:
      context: https://${GITHUB_TOKEN}@github.com/bchrobot/metagenscope-server.git
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:5000 manage:app
    environment:
      - APP_SETTINGS=production

  web-service:
    build:
      context: https://${GITHUB_TOKEN}@github.com/bchrobot/metagenscope-client.git
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - REACT_APP_METAGENSCOPE_SERVICE_URL=http://test.metagenscope.com

  e2e:
    container_name: e2e
    build:
      context: ./e2e/
      args:
        - TEST_URL=http://test.metagenscope.com
    # Run service indefinitely so we can test and then copy artifacts from the same instance
    entrypoint: tail -F -n0 /etc/hosts
    depends_on:
      nginx:
        condition: service_started
    links:
      - "nginx:test.metagenscope.com"
