version: '3.5'

services:

  swagger:
    container_name: swagger
    build:
      context: https://github.com/bchrobot/metagenscope-swagger.git
    ports:
      - '8081:8080' # expose ports - HOST:CONTAINER
    environment:
      - API_URL=https://raw.githubusercontent.com/MetaGenScope/metagenscope-swagger/master/swagger.yml
    depends_on:
      metagenscope-service:
        condition: service_started
