version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.2.0-browsers
    environment:
      TEST_URL: http://127.0.0.1
      REACT_APP_METAGENSCOPE_SERVICE_URL: http://127.0.0.1
      DISPLAY: ':99.0'

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            set -x
            VER="1.11.2"
            curl -L https://github.com/docker/compose/releases/download/${VER}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - setup_remote_docker

      - run:
          name: Start container
          command: |
            set -x
            sh -e /etc/init.d/xvfb start
            sleep 3
            docker-compose up --build -d

      # run tests!
      - run:
          name: run tests
          command: sh test.sh

      - run:
          name: Stop container
          command: docker-compose down
