version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.2.0
    environment:
      REACT_APP_METAGENSCOPE_SERVICE_URL: http://metagenscope-service
      DISPLAY: ':99.0'

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Node modules
          command: |
            npm install --silent

      - run:
          name: Install Docker Compose
          command: |
            set -x
            VER="1.11.2"
            curl -L https://github.com/docker/compose/releases/download/${VER}/docker-compose-`uname -s`-`uname -m` > docker-compose
            chmod +x docker-compose
            sudo mv docker-compose /usr/local/bin

      - setup_remote_docker

      - run:
          name: Build and start containers
          command: |
            set -x
            docker-compose -f docker-compose.ci.yml up --build -d
            docker-compose -f docker-compose.ci.yml exec metagenscope-service python manage.py recreate_db

      - run:
          name: Lint e2e tests
          command: |
            set -x
            docker-compose -f docker-compose.ci.yml exec e2e npm run lint

      - run:
          name: Run tests
          command: |
            set -x
            sh test.sh

      - run:
          name: Copy artifacts
          when: always
          command: |
            docker cp e2e:/usr/src/app/test-artifacts ./test-artifacts

      - store_artifacts:
          path: ./test-artifacts
          destination: test-reports

      - run:
          name: Stop container
          when: always
          command: docker-compose down --remove-orphans
