version: 2

jobs:
  build:
    docker:
      - image: debian:jessie
    environment:
      REACT_APP_METAGENSCOPE_SERVICE_URL: http://emptyfish.net

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install curl
          command: apt-get update; apt-get install -y curl

      - run:
          name: Install Docker Compose
          command: |
            set -x
            VER="1.11.2"
            curl -L https://github.com/docker/compose/releases/download/${VER}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - setup_remote_docker

      - run:
          name: Start container
          command: |
            set -x
            docker-compose up --build -d

      # run tests!
      - run:
          name: run tests
          command: docker-compose run metagenscope-service python manage.py test

      - run:
          name: Stop container
          command: docker-compose down
