version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.2.0-browsers
    environment:
      REACT_APP_METAGENSCOPE_SERVICE_URL: metagenscope-service
      DISPLAY: ':99.0'

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Node modules
          command: |
            npm install --silent

      - run:
          name: Install Docker Compose
          command: |
            set -x
            VER="1.11.2"
            curl -L https://github.com/docker/compose/releases/download/${VER}/docker-compose-`uname -s`-`uname -m` > docker-compose
            chmod +x docker-compose
            sudo mv docker-compose /usr/local/bin

      - run:
          name: Install Docker Machine
          command: |
            set -x
            VER="0.13.0"
            curl -L https://github.com/docker/machine/releases/download/${VER}/docker-machine-`uname -s`-`uname -m` > docker-machine
            chmod +x docker-machine
            sudo mv docker-machine /usr/local/bin

      - setup_remote_docker

      - run:
          name: Start container
          command: |
            set -x
            docker-compose up --build -d

      # Run tests!
      - run:
          name: Run tests
          command: |
            set -x
            export TEST_URL=`docker-machine ip`
            docker-compose run metagenscope-service python manage.py test
            npm test

      - run:
          name: Stop container
          command: docker-compose down
